---

- name: Configurar servidor de banco de dados
  hosts: db01
  
  user: vagrant
  become: yes
  vars_files:
    - vars/main.yaml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpasswords: devopsmaonamassa
  tasks:
    - name: Configurar hosts do ansible
      linefile: line "{{item}}" path=/etc/hosts
      with_itens:
        - 192.168.56.2 control-node
        - 192.168.56.3 app01
        - 192.168.1.4 db01
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql